#!/bin/sh

echo -e "Branch name validation started ..."
localBranchName="$(git rev-parse --abbrev-ref HEAD)"
validBranchRegex="^(feature|bugfix|improvement|hotfix|task)\/(task\-[0-9]+\_)+[a-zA-Z0-9_-]+$"

Red="\033[0;31m" 
Green="\033[0;32m"
Color_Off="\033[0m"

errorMessage="${Red}Branch name validation failed.\n\nBranch names in this project must adhere to this contract: \
$validBranchRegex\nYour commit will be rejected. You should rename your branch to a valid name and try again. \
${Color_Off}\n\nExample: \"feature/task-123_Branch_Name\".\n"

if [[ ! $localBranchName =~ $validBranchRegex ]]
then
    echo -e "$errorMessage" >&2
    exit 1
fi

echo -e "${Green}Branch name validation passed.${Color_Off}"
exit 0
